services:
    frontend:
      build: .
      image: frontend
      ports:
        - "80:80"
      networks:
        test:
            ipv4_address: 172.23.0.1
networks:
  test:
    external:
      name: testNetwork2