services:
    frontend:
      build: .
      image: frontend
      ports:
        - "8080:8080"
      networks:
        test:
            ipv4_address: 172.23.1.1
networks:
  test:
    external:
      name: testNetwork2